version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: singlezoo
    ports:
      - "2180:2180"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: singlekafka
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: singlezoo:2180
#      KAFKA_CREATE_TOPICS: "chat:3:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - zookeeper
#    networks:
#      - test